//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEconomyAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serie
    {
        public int id { get; set; }
        public int projectId { get; set; }
        public int initial { get; set; }
        public int end { get; set; }
        public Nullable<decimal> downPayment { get; set; }
        public Nullable<decimal> finalPayment { get; set; }
        public decimal quantity { get; set; }
        public Nullable<decimal> present { get; set; }
        public Nullable<decimal> future { get; set; }
        public string type { get; set; }
        public string flowType { get; set; }
        public decimal rate { get; set; }
        public bool incremental { get; set; }
        public int totalPeriod { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
